# Generated by Django 4.2.4 on 2023-09-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_criteria"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excel_file", models.FileField(upload_to="excel_files/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="criteria",
            field=models.TextField(
                default='{"C": 1, "T": 2, "S": 0}',
                verbose_name="Criteria JSON (DONT FILL THIS)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="has_filled_profile",
            field=models.BooleanField(default=True, verbose_name="Has Filled Profile"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_phone_no_verified",
            field=models.BooleanField(
                default=True, verbose_name="Is Phone Number Verified"
            ),
        ),
    ]
