# Generated by Django 4.2.4 on 2023-09-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_exceldata_alter_user_criteria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrequest",
            name="college",
            field=models.CharField(blank=True, max_length=256, verbose_name="College"),
        ),
    ]
