# Generated by Django 4.2.4 on 2023-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="userpassword",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
