# Generated by Django 4.2.4 on 2023-09-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_userpassword_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_send",
            field=models.BooleanField(default=False, verbose_name="Email Send"),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Comp A", "Computer A"),
                    ("Comp B", "Computer B"),
                    ("IT", "IT"),
                    ("EXTC", "EXTC"),
                    ("Mech A", "Mechanical A"),
                    ("Mech B", "Mechanical B"),
                    ("Elec", "Electrical"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
                null=True,
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="userrequest",
            name="department",
            field=models.CharField(
                choices=[
                    ("Comp A", "Computer A"),
                    ("Comp B", "Computer B"),
                    ("IT", "IT"),
                    ("EXTC", "EXTC"),
                    ("Mech A", "Mechanical A"),
                    ("Mech B", "Mechanical B"),
                    ("Elec", "Electrical"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
                verbose_name="Department",
            ),
        ),
    ]
