# Generated by Django 4.2.4 on 2023-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_email_send_alter_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Roll Number'),
        ),
    ]
