# Generated by Django 4.2.4 on 2023-09-07 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userrequest_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participation',
            name='captain_paid',
            field=models.BooleanField(default=False, verbose_name='captain paid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='criteria',
            field=models.TextField(default='{"C": 0, "T": 0, "S": 0}', verbose_name='Criteria JSON (DONT FILL THIS)'),
        ),
    ]
