# Generated by Django 4.2.4 on 2023-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_google_link',
            field=models.URLField(blank=True, null=True, verbose_name='Google drive'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('C', 'Cultural'), ('T', 'Seminar'), ('S', 'Sports')], max_length=1, verbose_name='Category'),
        ),
    ]
