# Generated by Django 4.2.4 on 2023-09-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_image_google_link_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Event Banner'),
        ),
    ]
